import "./globals.scss";
import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import LenisProvider from "@/hooks/LenisProvider";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${bricolageGrotesque.variable} text-stone-900 dark:text-white bg-white dark:bg-stone-950 antialiased`}
        >
          <LenisProvider />
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
